apiVersion: v2
name: jhub-helm
description: A Helm chart to deploy JupyterHub on Kubernetes

type: application

version: 0.1.0
appVersion: "2.0.1"

dependencies:
  - name: jupyterhub
    version: "2.0.1-0.dev.git.6105.hb969fa50"
    repository: https://jupyterhub.github.io/helm-chart/