persistentVolume:
  jhubVolume:
    name: helm-jhub-volume
    path: /tmp
    type: local

hostname: __JHUB_HOSTNAME__
ingress: false 
jupyterhub:
  cull:
    enabled: true 
  hub:
    db:
      type: sqlite-pvc
      upgrade:
      pvc:
        annotations: {}
        selector: {}
        accessModes:
          - ReadWriteOnce
        storage: 1Gi
        subPath:
        storageClassName: local-storage
    image:
      name: biancoj/jhub-asyncio
      tag: 5.0.1
    cookieSecret: __COOKIE_SECRET__
    extraVolumes:
      - name: jhub-config
        configMap:
          name: jhub-config
          items:
           - key: jupyterhubcustomconfig.py
             path: jupyterhubcustomconfig.py
    extraVolumeMounts:  
      - name: jhub-config
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/
    extraConfig:
      00-first-config: |
        config_py = open('/usr/local/etc/jupyterhub/jupyterhub_config.d/jupyterhubcustomconfig.py').read()
        exec(config_py)
    args:
    - jupyterhub
    - --config
    - /usr/local/etc/jupyterhub/jupyterhub_config.py
    - --upgrade-db
    extraEnv:
      OAUTH_CALLBACK_URL: __CALLBACK_URL__
      OAUTH_ENDPOINT: __IAM_SERVER__
      OAUTH_GROUPS: users 
  ingress:
    enabled: false 
  proxy:
    service:
      type: ClusterIP
    secretToken: __COOKIE_SECRET__
  scheduling:
    podPriority:
      enabled: false
    userPlaceholder:
      enabled: false
    userScheduler:
      enabled: false
  singleuser:
    storage:
      type: none
      dynamic:
        storageClass: null
        pvcNameTemplate: null
        volumeNameTemplate: null
    startTimeout: 600
    uid: 0
    cloudMetadata:
      blockWithIptables: false