apiVersion: v1
kind: PersistentVolume
metadata:
 name: {{ .Values.persistentVolume.jhubVolume.name }}
 labels:
   type: {{ .Values.persistentVolume.jhubVolume.type }}
spec:
 capacity:
   storage: 1Gi
 volumeMode: Filesystem
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Delete
 storageClassName: local-storage
 local:
   path: {{ .Values.persistentVolume.jhubVolume.path }}
 nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists